# Generated by Django 2.1 on 2018-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('thumb_id', models.CharField(max_length=100)),
                ('shift_id', models.CharField(max_length=100)),
                ('paid_leaves', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=20)),
                ('user_type', models.CharField(max_length=100)),
                ('del_flag', models.CharField(max_length=100)),
            ],
        ),
    ]
