# Generated by Django 2.1 on 2018-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='del_flag',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='paid_leaves',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift_id',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(max_length=100),
        ),
    ]
