# Generated by Django 2.1 on 2018-08-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0002_auto_20180803_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='del_flag',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='paid_leaves',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(),
        ),
    ]
