# Generated by Django 2.1 on 2018-08-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0003_auto_20180803_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=100)),
                ('thumb_id', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=100)),
                ('in_out_flag', models.CharField(max_length=20)),
                ('shift_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_time', models.CharField(max_length=100)),
                ('to_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='del_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='shift_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumb_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
