# Generated by Django 2.1 on 2018-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0004_auto_20180803_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
    ]
