# Generated by Django 2.1 on 2018-08-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0005_auto_20180803_1059'),
        ('masterApp', '0005_auto_20180803_1053'),
    ]

    operations = [
    ]
