# Generated by Django 2.1 on 2018-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0007_auto_20180805_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='user',
            name='del_flag',
            field=models.IntegerField(default=1),
        ),
    ]
