# Generated by Django 2.1 on 2018-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0009_auto_20180808_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='holidays',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
