# Generated by Django 2.1 on 2018-08-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0012_paidleaves_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidleaves',
            old_name='no_of_dyas',
            new_name='no_of_days',
        ),
    ]
