# Generated by Django 2.1 on 2018-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApp', '0013_auto_20180808_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidleaves',
            name='no_of_days',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.IntegerField(max_length=20),
        ),
    ]
